version: '3'

services:
  web:
    container_name: pt_wordpress_web
    image: wordpress:latest
    restart: always
    networks:
      - default
    volumes:
      - ./webserver/html:/var/www/html
      - ./webserver/config/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    ports:
      - "${WEB_SERVER_PORT}:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${DB_USERNAME}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}

  db:
    container_name: pt_wordpress_database
    image: mariadb:latest
    restart: always
    networks:
      - default
    volumes:
      - ./mariadb/data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}

  phpmyadmin:
    container_name: pt_wordpress_phpmyadmin
    image: phpmyadmin:latest
    restart: always
    networks:
      - default
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      - UPLOAD_LIMIT=256M

networks:
  default:
    name: ${NETWORK_NAME}
    external: true